version: '3'
services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cat
      MYSQL_PASSWORD: cat
      MYSQL_DATABASE: cat

  cat:
    build: .
    command: bundle exec hanami server --host 0.0.0.0 -p 2300
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cat
      MYSQL_PASSWORD: cat
      MYSQL_DATABASE: cat
      MYSQL_HOST: db
    volumes:
      - ".:/cat"
    ports:
      - "2300:2300"
    depends_on:
      - db
    links:
      - db
